### ISSUE TITLE
tracking bug: stages

### ISSUE THREAD

**Issue by mo271** [libjxl/jxl-rs#58]
- [x] blending
- [x] chroma_upsample (-> chroma_upsample.rs)
- [x] epf (-> epf.rs)
- [x] from_linear (-> from_linear.rs)
- [x] gaborish (-> gaborish.rs)
- [x] noise (-> noise.rs)
- [x] patches (-> patches.rs)
- [x] splines (-> splines.rs)
- [x] spot (-> spot.rs)
- [x] to_linear (-> to_linear.rs)
- [ ] tone_mapping (WIP @OneDeuxTriSeiGo)
- [x] upsampling (-> upsample.rs)
- [x] write (-> save.rs)
- [x] xyb (-> xyb.rs)
- [x] ycbcr (-> ycbcr.rs)

**Comment by jonnyawsom3** [comment]
As far as I can tell, Noise and Splines are now implemented

**Comment by mo271** [comment]
> As far as I can tell, Noise and Splines are now implemented

Noises is almost ready (some tests are missing), but for splines, only the decoding of the bitstream is there, digesting the data in a format that can be used to draw the splines and using them in a stage is still missing.

**Comment by jonnyawsom3** [comment]
Ahh right, I'll leave it to the actual contributors to update this

**Comment by eustas** [comment]
Just checked: only `tone_mapping` and `blending` stages seem to be absent.

That does not necessarily mean that `from_linear`, `spot`, `to_linear` and `ycbcr` are 100% ready.
@inflation, @OneDeuxTriSeiGo - could you please confirm?

**Comment by OneDeuxTriSeiGo** [comment]
I'm working on `tone_mapping` at the moment.

**Comment by eustas** [comment]
Awesome, thanks for update!

**Comment by OneDeuxTriSeiGo** [comment]
A few months back I tried to get a handle on status for things before I started trying to contribute and this was the status list I came up with. It'd need to be updated to between Feb and now of course but idk if it'd be useful.

[tracking_list.md](https://github.com/user-attachments/files/20197590/tracking_list.md)

**Comment by jpc-ae** [comment]
@OneDeuxTriSeiGo how is `tone_mapping ` coming along? That seems to be the only thing left on this list.

**Comment by veluca93** [comment]
I'd argue at this point that we don't really need a tone mapping stage, and we can leave it to the application - closing this :-)
